### PR TITLE
ádded a friendler at some part of it

### PR DESCRIPTION
**Pull request by ShovelTime**
i meant a friendlier choice system

### CODE REVIEW

**Comment by ShovelTime** [comment]
hold on dont use this one its bugged

**Comment by ShovelTime** [comment]
dont merge it yet

**Comment by o-be-one** [comment]
Yup no problem, why did you used break ? I thin kthats why it doesn't work ?

**Comment by ShovelTime** [comment]
no its because the character befor the ) has to be quoted  the new pull request i made fixes that

**Comment by ShovelTime** [comment]
the break has to be put or else the command will constantly loop and will never move on

**Comment by o-be-one** [comment]
I've never used the "select" command, good to know thanks a lot !
But by your PR, we can't do a selection like "134", we have to restart the script for each component. With the previous way, we was able to select what we want in just one time.

What you think about it ?

**Comment by ShovelTime** [comment]
oh, i never noticed that before, il found a way around that

**Comment by o-be-one** [comment]
I've updated the readme to explain what are other scripts in this repo, did you noticed it ?

**Comment by ShovelTime** [comment]
yep

On 4 April 2016 at 16:28, Meddy B. notifications@github.com wrote:

> I've updated the readme to explain what are other scripts in this repo,
> did you noticed it ?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/o-be-one/git-deploy-linux/pull/3#issuecomment-205321582

## 

Erik

## 

This email and any attachments to it may be confidential and are intended 
solely for the use of the individual to whom it is addressed. Any views or 
opinions expressed are solely those of the student author and do not 
necessarily represent those of the Stockholm International School. If you 
are not the intended recipient of this email, you must neither take any 
action based upon its contents, nor copy or show it to anyone.Please 
forward this email to the school IT Office it@intsch.se if you believe you 
have received this email in error or if it contains inappropriate content.

**Pull request closed without merging**
